# Generated by Django 5.0.7 on 2024-08-11 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0036_alter_eventdata_options_alter_gallerydata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerydata',
            name='gallery_event_type',
            field=models.CharField(blank=True, choices=[('music', 'music'), ('entertainment', 'entertainment')], max_length=100, null=True, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 16, 33, 50, 770055), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 11, 16, 33, 50, 771060), verbose_name='Event Time'),
        ),
    ]
