# Generated by Django 5.0.7 on 2024-08-11 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0037_gallerydata_gallery_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 16, 36, 6, 952751), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 11, 16, 36, 6, 953768), verbose_name='Event Time'),
        ),
    ]
