# Generated by Django 5.0.7 on 2024-08-12 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0039_alter_contactformsubmission_event_date_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 19, 59, 39, 332305), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 11, 19, 59, 39, 333317), verbose_name='Event Time'),
        ),
    ]
