# Generated by Django 5.0.7 on 2024-08-12 18:26

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0040_alter_contactformsubmission_event_date_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 12, 12, 26, 1, 896199), verbose_name='Event Time'),
        ),
    ]
