# Generated by Django 5.0.7 on 2024-08-12 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0041_alter_contactformsubmission_event_date_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 12, 12, 28, 0, 483172), verbose_name='Event Time'),
        ),
    ]
